### ISSUE TITLE
能标记Maker，自定义Maker图标吗？

### ISSUE THREAD

**Issue by daffy6537** [react-native-component/react-native-smart-amap#1]

**Comment by daffy6537** [comment]
类似摩拜单车这种，可以标记位置，并把图标换成小车，同时可以使特定的Maker显示active状态下的图标， 也可以拖动位置，查看周边的list，标记上去

**Comment by cyqresig** [comment]
高德地图SDK具备这些功能，暂时还没封装的这么细，后续会进一步做封装
