### ISSUE TITLE
求教：rn 0.43 下面 调用地图不显示

### ISSUE THREAD

**Issue by taixiang** [react-native-component/react-native-smart-amap#16]
我是这样调用的 ，经纬度传值也是正常的，但是界面没有显示地图，用的android调试的，求教！
谢谢！
<AMap
					ref={ component => this._amap = component }
					options={{
						frame: {
							width: window.width,
							height: window.height
						},
						showsUserLocation: false,
	  					userTrackingMode: Platform.OS == 'ios' ?                        AMap.constants.userTrackingMode.none : null,
						centerCoordinate: {
							latitude: this.props.route.lat,
							longitude: this.props.route.lng,
						},
						zoomLevel: 18.1,
						centerMarker: Platform.OS == 'ios' ? 'icon_location' : 'poi_marker',
					}}
					style={{flex:1}}
					onLayout={this._onLayout}
				/>

**Comment by tears743** [comment]
找到原因了么，我是0.49也不显示
